# Generated by Django 3.2.9 on 2021-11-21 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_isAdmin',
        ),
    ]
