# Generated by Django 3.2.9 on 2021-12-01 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('register', '0002_remove_client_client_isadmin'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Client',
        ),
    ]
